// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreShoppingCartApplication.Models;

namespace coreShoppingCartApplication.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211222041542_ProductDataSeeding")]
    partial class ProductDataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("coreShoppingCartApplication.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://d3nn873nee648n.cloudfront.net/900x600/8384/5-SM205485.jpg",
                            Name = "Product One",
                            Price = 234.0
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://d3nn873nee648n.cloudfront.net/900x600/8384/5-SM205485.jpg",
                            Name = "Product Two",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://d3nn873nee648n.cloudfront.net/900x600/8384/5-SM205485.jpg",
                            Name = "Product Three",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://d3nn873nee648n.cloudfront.net/900x600/8384/5-SM205485.jpg",
                            Name = "Product Four",
                            Price = 400.0
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://d3nn873nee648n.cloudfront.net/900x600/8384/5-SM205485.jpg",
                            Name = "Product Five",
                            Price = 350.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
